### PR TITLE
Add methods to iterate over matching config/data files

### PR DESCRIPTION
**Pull request by takluyver**
I suspect that I'm doing this in a clumsy way, so don't hesitate to point out if it can be made more elegant!

Closes gh-19

### CODE REVIEW

**Comment by whitequark** [comment]
Remember that snippet I gave you in #19? Note the return type of `chain` there and make `FileFindIterator` a newtype over it. Boom, done.

**Comment by takluyver** [comment]
Sorry, I'm not getting it. The return type is `std::iter::Chain`, I think? But that wants type parameters which I'm not sure about, and lifetime specifiers which I'm even less sure about.

**Comment by takluyver** [comment]
I've tried a few more things, but none of them compile. I think I don't understand how to properly work with abstract things like iterators in Rust - I can only make it work by converting everything to concrete, owned objects like `Vec`.

**Comment by takluyver** [comment]
If it's easier for you to do this yourself, feel free to do so, and I'll try to understand it by looking at your code.

**Comment by whitequark** [comment]
Just haven't had any time, sorry! It's sitting in my review queue. I'll take a look soon.

**Comment by takluyver** [comment]
Thanks, no rush :-)

**Comment by whitequark** [comment]
Thanks for the PR!

**Comment by takluyver** [comment]
Thanks :-). If you can see a smarter way to do it with iterators, I'm happy to learn.

**Pull request merged**
