### PR TITLE
Add support for "profiles" in user-specific directories.

### PR DESCRIPTION
**Pull request by SimonSapin**
See doc-comment.

Bumping to 2.1 as it’s a new feature. (By the way, what does "pre" mean to you in version numbers?)

### CODE REVIEW

**Comment by whitequark** [comment]
You don't have to bump, because the currently published version is a pre-release. See paragraph 9 on http://semver.org/.

**Comment by whitequark** [comment]
Otherwise LGTM.

**Comment by SimonSapin** [comment]
Amended. (Should Cargo handle pre-releases specially?)

**Comment by whitequark** [comment]
I worked under assumption that it does (i.e. `*` or `~> 2.0` do not include pre-releases; this is what e.g. Ruby's Bundler does). Is that not the case?

**Comment by SimonSapin** [comment]
I don’t know. @alexcrichton, how does Cargo treat pre-release version numbers?

**Comment by alexcrichton** [comment]
Currently Cargo doesn't treat pre-release versions specially, the behavior just falls out of the standard logic for comparing semver versions

**Comment by whitequark** [comment]
@alexcrichton Actually, it does not. If I put `xdg = "2.0"` or `xdg = ">= 2.0"` in Cargo.toml, Cargo selects `2.0.0-pre5`, which is in clear contradiction of the semver spec, paragraph 11

**Pull request merged**
