### PR TITLE
Windows support for Base Directories spec

### PR DESCRIPTION
**Pull request by ErichDonGubler**
Hey there! Not sure how interesting this is for this repo, but this is some experimental support I've been working on while (1) learning about the Windows permissions model and (2) making [Capisco](https://github.com/capisco-dotfiles/capisco), a side project of mine. I think that this should actually work fairly well, notwithstanding some testing.

See commit messages for details on implementation design; I've tried to create a "nice" abstraction for file permissions as part of this PR. :)

Merge checklist:
- [ ] Resolve outstanding `TODO` commentary.
- [ ] Test on Linux -- I've done testing on Windows, and have done a minor review pass, but I think it'd be best to just prove that all tests still pass.

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
@whitequark: You're correct that the [entire corpus of XDG specs](https://specifications.freedesktop.org/) are targeted towards *nix platforms, and I definitely don't think that all (most?) of them would make sense for Windows. That said, the [XDG Base Directories specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is actually very portable[^1], and has been used for years now in ecosystems that offer POSIX-like environments in Windows, like the [MSYS2](https://www.msys2.org/) [ecosystem](https://packages.msys2.org/package/) (which powers [Git for Windows](https://gitforwindows.org)).

I didn't take any time to design a longer-term solution for (since I wasn't sure what other specs you may have ambitions for implementing), but I'd be happy to offer one and/or work with you to find one. :) 


[^1]: With some interpretation of how `0700` translates to Windows ACLs, that is. I've taken what is IMO the strictest practical interpretation in this PR.

**Comment by whitequark** [comment]
That's true. To be more precise, I consider only *nix platforms to be in scope for the `xdg` crate.

**Comment by ErichDonGubler** [comment]
An alternative to this PR for my purposes might be to `cfg(unix)` the `XDG_RUNTIME_DIR` portions of this crate, making it an opt-out `feature` in Cargo. I don't currently use those directories, and it'd be a much smaller PR. I imagine somebody might find what I wrote useful for Windows support eventually, but I understand if you don't want to maintain a bunch of Windows-specific logic.

**Comment by whitequark** [comment]
I think there's a few more issues, like the `XDG_CONFIG_DIRS` variable that's defaulted to `/etc/xdg`.

**Comment by ErichDonGubler** [comment]
I'll close this PR, since it seems obvious to me that this implementation direction is infeasible according to your crate design goals.

> I think there's a few more issues, like the `XDG_CONFIG_DIRS` variable that's defaulted to `/etc/xdg`.

Yes, global paths would need to be audited/conditionally used too, to be consistent with my suggestion. That's a good point.

**Pull request closed without merging**
