### PR TITLE
Move to the smaller, cargo-team maintained `home` crate

### PR DESCRIPTION
**Pull request by utkarshgupta137**

### CODE REVIEW

**Comment by whitequark** [comment]
This fails a CI check, could you take a look please?

**Comment by utkarshgupta137** [comment]
Looks like the `home` crate targets MSRV of `1.36`: https://github.com/rust-lang/cargo/blob/master/crates/home/CHANGELOG.md#053---2020-01-07. It's your call to raise the MSRV of your crate or not.

**Comment by whitequark** [comment]
Yeah I think we can live with an MSRV from 2019. Can you update the PR please?

**Comment by whitequark** [comment]
Thanks!

**Comment by utkarshgupta137** [comment]
Might be time for a new release?

**Comment by whitequark** [comment]
Will do a bit later

**Comment by whitequark** [comment]
Maybe after https://github.com/whitequark/rust-xdg/issues/62 gets resolved?

**Comment by whitequark** [comment]
Nevermind, released 2.5.0.

**Pull request merged**
