### PR TITLE
Make the library run on 1.2.0 and stable

### PR DESCRIPTION
**Pull request by tbu-**
Relevant for https://github.com/rust-lang/cargo/pull/2127.

### CODE REVIEW

**Comment by tbu-** [comment]
I installed `multirust` and tested this locally, should work. The tests don't compile on stable/1.2.0.

Fixes the errors reported at https://travis-ci.org/rust-lang/cargo/builds/90258059.

**Comment by whitequark** [comment]
LGTM, do you think you could also update `.travis.yml` to include stable?

**Comment by tbu-** [comment]
The tests currently don't compile on stable, should I fix that too?

**Comment by tbu-** [comment]
@whitequark Tests run on all versions now.

**Comment by whitequark** [comment]
Wonderful, thanks!

**Comment by whitequark** [comment]
Released pre5.

**Comment by tbu-** [comment]
Thanks for responding so quickly all the time! The cargo PR passes all its tests now.

**Pull request merged**
